# Generated by Django 5.0.1 on 2024-01-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tamaño', models.CharField(max_length=30)),
                ('masa', models.CharField(max_length=30)),
                ('ingrediente1', models.CharField(max_length=30)),
                ('ingrediente2', models.CharField(max_length=30)),
                ('ingrediente3', models.CharField(max_length=30)),
                ('ingrediente4', models.CharField(max_length=30)),
            ],
        ),
    ]
