# Generated by Django 5.0.1 on 2024-01-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPizzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('cod_ases', models.IntegerField(max_length=8)),
                ('correo', models.EmailField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Creador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField(max_length=2)),
                ('correo', models.EmailField(max_length=8)),
            ],
        ),
    ]
