# Generated by Django 5.0.1 on 2024-01-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPizzas', '0002_asesor_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesor',
            name='cod_ases',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='creador',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='creador',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
